#!/bin/sh

. /lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if component_was_executed "gnome-shortcuts"
	then
		exit 0
	fi

	echo -n " gnome-shortcuts"
}

Config ()
{
	sudo -u $LIVE_USERNAME dbus-run-session -- /usr/local/bin/set-shortcuts.sh
	touch /var/lib/live/config/gnome-shortcuts
}

Cmdline
Init
Config
