name: Preseed

on: push

jobs:
  preseed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Make all targets
        run: make all
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Release preseed files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/gnome.cfg
            ./build/cursus.cfg
            ./build/server.cfg
            ./build/personal.cfg
            ./build/complete.cfg
            ./build/scripts.tar.gz
